### PR TITLE
MAJOR reorganization and added tags

### PR DESCRIPTION
**Pull request by Clockmaker**
In short:
* splitted math and programming
* added calculus
* moved FEA section
* splitted mechanics and machines
* removed orphan/empty sections
* removed that _controversial_ quora.
* removed random bibtex
* started a tag system for readability and easy navigation

Problems:
 * The preamble is still there, but imho we already have an introduction.
 * still missing CAD software
 * too many random ISBN
 * the list should prioritize Free and OpenAccess

### CODE REVIEW

**Review by pwab — APPROVED** [review]
Good job! Love it 👍

**Comment by pwab** [comment]
> The preamble is still there, but imho we already have an introduction.

Could be removed imho.

> still missing CAD software

How about adding an issue so we don't forget? 😅 

> too many random ISBN

I do prefer ISBN to amazon links. It is easier to work with ISBN, DOI etc. when dealing with citation management software.

> the list should prioritize Free and OpenAccess

This is imho the central point of this list. So I would like to note that these amazon links and isbns are leading to paid content and therefore should be removed.

**Comment by m2n037** [comment]
This was awesome. Thanks a lot. :)

**Comment by Clockmaker** [comment]
my pleasure 😉

**Pull request merged**
